version: "3.8"

services:
  bot:
    build: .
    image: in-house-queue-site
    container_name: inhousequeue-site
    environment:
      DATABASE_URL: ${DATABASE_URL}
      UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
      UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
      DISABLE_GUILD_CHECKING: ${DISABLE_GUILD_CHECKING}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      STATS_ENDPOINT: ${STATS_ENDPOINT}
    volumes:
      - ./src:/app/src
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "3000:3000"
    networks:
      - inhouse-network
    depends_on:
      - website-stats

  website-stats:
    build:
      context: ../website-stats # https://github.com/InHouseQueue/website-stats
      dockerfile: Dockerfile
    image: website-stats
    container_name: website-stats
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - inhouse-network
    ports:
      - "5000:5000"

networks:
  inhouse-network:
    external: true

volumes:
  redis-data:
