name: Deploy Production
env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build_and_tag:
    runs-on: ubuntu-latest
    environment: Production
    services:
      docker:
        image: docker:19.03.5-dind
        options: --privileged

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            ref: live

        - name: Build Docker image
          run: |
            docker build -t in-house-queue-site \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            --build-arg DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} \
            --build-arg DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }} \
            --build-arg UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }} \
            --build-arg UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }} \
            .

        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

        - name: Log in to DigitalOcean Container Registry with short-lived credentials
          run: doctl registry login --expiry-seconds 600

        - name: Get the latest release tag
          id: latest_release
          run: |
            tag=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/releases/latest" | jq -r ".tag_name")
            echo "TAG=$tag" >> $GITHUB_ENV

        - name: Tag and push Docker image
          run: |
            export DO_REPOSITORY=${{ secrets.DO_REPO }}
            TAG=${{ env.TAG }}
            echo "Tagging image as $DO_REPOSITORY:$TAG"
            docker tag in-house-queue-site $DO_REPOSITORY:$TAG
            echo "Pushing image..."
            docker push $DO_REPOSITORY:$TAG